// Light Theme
const lightTheme = {
    container: {
      fontFamily: "Arial, sans-serif",
      padding: "20px",
      backgroundColor: "#fff",
      color: "#000",
      minHeight: "100vh",
    },
    controls: {
      marginBottom: "20px",
      display: "flex",
      gap: "10px",
      flexWrap: "wrap",
    },
    searchInput: {
      padding: "8px",
      fontSize: "1rem",
      borderRadius: "4px",
      border: "1px solid #ccc",
      flex: 1,
      backgroundColor: "#fff",
      color: "#000",
    },
    sortSelect: {
      padding: "8px",
      fontSize: "1rem",
      borderRadius: "4px",
      border: "1px solid #ccc",
      flex: 1,
      backgroundColor: "#fff",
      color: "#000",
    },
    nftGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
      gap: "20px",
      marginBottom: "20px",
    },
    nftCard: {
      backgroundColor: "#f9f9f9",
      borderRadius: "8px",
      padding: "20px",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      width: "100%",
      transition: "transform 0.2s, box-shadow 0.2s",
      "&:hover": {
        transform: "translateY(-4px)",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2)",
      },
    },
    imageContainer: {
      width: "150px",
      height: "150px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#f0f0f0",
      borderRadius: "8px",
      overflow: "hidden",
    },
    coverImage: {
      width: "100%",
      height: "100%",
      objectFit: "contain",
      borderRadius: "8px",
    },
    title: {
      fontSize: "1.2rem",
      margin: "8px 0",
      fontWeight: "bold",
      color: "#000",
    },
    author: {
      fontSize: "0.9rem",
      color: "#666",
      margin: "4px 0",
    },
    descriptionLink: {
      background: "none",
      border: "none",
      color: "#007bff",
      cursor: "pointer",
      fontSize: "0.9rem",
      margin: "4px 0",
      "&:hover": {
        textDecoration: "underline",
      },
    },
    tradeLink: {
      color: "#007bff",
      textDecoration: "none",
      fontSize: "0.9rem",
      margin: "4px 0",
      "&:hover": {
        textDecoration: "underline",
      },
    },
    popupOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
      overflow: "auto",
    },
    popupContent: {
      backgroundColor: "#fff",
      borderRadius: "8px",
      padding: "20px",
      maxWidth: "500px",
      width: "90%",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
      maxHeight: "90vh",
      overflowY: "auto",
      display: "flex",
      flexDirection: "column",
      margin: "20px",
    },
    iframeContainer: {
      flex: "0 0 auto",
      marginBottom: "16px",
      width: "100%",
    },
    interactiveIframe: {
      width: "100%",
      height: "200px",
      border: "none",
      borderRadius: "8px",
    },
    descriptionContainer: {
      flex: 1,
      overflowY: "auto",
      marginBottom: "16px",
      scrollbarWidth: "thin", // Standard property for Firefox
      scrollbarColor: "#888 transparent", // Standard property for Firefox
    },
    popupDescription: {
      fontSize: "1rem",
      color: "#000",
      margin: 0,
    },
    buttonContainer: {
      display: "flex",
      justifyContent: "flex-end",
      gap: "10px",
    },
    expandButton: {
      background: "#28a745",
      border: "none",
      color: "#fff",
      padding: "8px 16px",
      borderRadius: "4px",
      cursor: "pointer",
      fontSize: "1rem",
    },
    closeButton: {
      background: "#007bff",
      border: "none",
      color: "#fff",
      padding: "8px 16px",
      borderRadius: "4px",
      cursor: "pointer",
      fontSize: "1rem",
    },
    readMoreButton: {
      background: "none",
      border: "none",
      color: "#007bff",
      cursor: "pointer",
      fontSize: "0.9rem",
      padding: "0",
      marginTop: "8px",
      "&:hover": {
        textDecoration: "underline",
      },
    },
    pagination: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "10px",
      marginTop: "20px",
    },
    toggleButton: {
      background: "#007bff",
      border: "none",
      color: "#fff",
      padding: "8px 16px",
      borderRadius: "4px",
      cursor: "pointer",
      fontSize: "1rem",
    },
    loadingSpinner: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: "200px",
      fontSize: "1.5rem",
      color: "#666",
    },
  };
  
  // Dark Theme
  const darkTheme = {
    ...lightTheme,
    container: {
      ...lightTheme.container,
      backgroundColor: "#121212",
      color: "#fff",
    },
    searchInput: {
      ...lightTheme.searchInput,
      backgroundColor: "#333",
      color: "#fff",
      border: "1px solid #555",
    },
    sortSelect: {
      ...lightTheme.sortSelect,
      backgroundColor: "#333",
      color: "#fff",
      border: "1px solid #555",
    },
    nftCard: {
      ...lightTheme.nftCard,
      backgroundColor: "#1e1e1e",
      color: "#fff",
    },
    title: {
      ...lightTheme.title,
      color: "#fff",
    },
    author: {
      ...lightTheme.author,
      color: "#bbb",
    },
    popupContent: {
      ...lightTheme.popupContent,
      backgroundColor: "#1e1e1e",
      color: "#fff",
    },
    popupDescription: {
      ...lightTheme.popupDescription,
      color: "#fff",
    },
  };
  
  export { lightTheme, darkTheme };